### ISSUE TITLE
Wrong parameter in post sets documentation

### ISSUE THREAD

**Issue by faucetlol** [DonovanDMC/E621Documentation#2]
https://github.com/DonovanDMC/E621Documentation/blob/a949444bf38b70e145b40d4c2bef24277e3b37b8/post_sets.md?plain=1#L153-L154

Not sure how I did this wrong, this should be `post_set[shortname]`. Didn't want more PR hassle so just made an issue instead.

**Comment by DonovanDMC** [comment]
I appreciate you not opening a pr actually, I've been mulling over things locally and plan on converting this documentation to being mostly generated, to make things like authorization comments and shared parameters consistent

It's been in the works for a while, as I generally lack motivation 🫠

**Comment by DonovanDMC** [comment]
Only took like 6 months, but it's a done deal
https://docs.e621.ws/post_sets#create-post-set

**Comment by DonovanDMC** [comment]
@faucetlol by the way, if you have any ideas for an alternative to gitbook, I'd love to hear them. Gitbook is an absolute buggy mess, and I hate working with it
Syncing just broke so I can't sync in new changes, and their team is gone for several days thanks to the timing

**Comment by faucetlol** [comment]
Read the Docs, perhaps? I've only experimented with that a little, so I'm not sure if it does everything you'll need, but it's _actually_ free and open source as far as I can remember.
