### ISSUE TITLE
Generate swagger JSON file alongside Documentation

### ISSUE THREAD

**Issue by fenpaws** [DonovanDMC/E621Documentation#3]
Hey, first of all, awesome project. The original documentation is quite lackluster, and you are a godsend for making this unofficial documentation. It helps so much!

Anyway, since you already generate Swagger for GitBooks, is it also possible to generate a normal Swagger JSON file alongside the documentation? It would help others, and me, to generate quickly a usable base layer for any other programming language. I'm currently working on a GoLang-based SDK/API Integration for e621, and this would help to speed it up.

Maybe GitBooks does it automatically, but I couldn't find anything.

Cheers!

**Comment by DonovanDMC** [comment]
https://github.com/DonovanDMC/E621OpenAPI now exists with a full OpenAPI spec
